<?php

namespace App\Helpers;

class LocalizationHelper
{
    private static array $dictionary = [
        'en' => [
            // Storefront Navbar & Global
            'nav_home' => 'Home',
            'nav_shop' => 'All Products',
            'nav_categories' => 'Categories',
            'nav_deals' => 'Flash Deals',
            'nav_track' => 'Track Order',
            'nav_spin' => 'Lucky Spin',
            'nav_ai' => 'Aura AI Bot',
            'nav_cart' => 'Cart',
            'nav_wishlist' => 'Wishlist',
            'nav_account' => 'My Account',
            'nav_login' => 'Login / Register',
            'nav_admin' => 'Admin Command Center',
            'search_placeholder' => 'Search cyber gear, mechanical keyboards, ANC earbuds...',
            'free_shipping_notice' => 'Express delivery across all 64 districts in Bangladesh',
            'currency_symbol' => '৳',
            'spin_win_btn' => 'SPIN & WIN',

            // Home & Hero Section
            'hero_badge' => '⚡ NEXT-GEN GADGETS & LIFESTYLE • BANGLADESH',
            'hero_title_line_1' => 'DISCOVER THE',
            'hero_title_gradient' => 'CYBER REVOLUTION',
            'hero_subtitle' => 'Elevate your life with ultra-responsive mechanical setups, holographic smart wearables, planar ANC audio, and GaN power stations. Delivered across Bangladesh within 24-48 hours.',
            'hero_btn_shop' => 'Explore Catalog',
            'hero_btn_spin' => 'Spin & Win ৳500',
            'stat_customers_count' => '50K+',
            'stat_customers_label' => 'BD Customers',
            'stat_delivery_count' => '24H',
            'stat_delivery_label' => 'Dhaka Express',
            'stat_genuine_count' => '100%',
            'stat_genuine_label' => 'Genuine Tech',
            'featured_card_badge' => '🔥 TOP CYBER GEAR',
            'featured_card_price' => '৳2,950 BDT',
            'featured_card_title' => 'AuraBlade ANC Pro',
            'featured_card_sub' => '45ms Low Latency • 48dB ANC',
            'featured_card_spec1' => 'v5.4 Dual Stream',
            'featured_card_spec2' => '40H Battery Life',
            'featured_card_btn' => 'View Cyber Details →',

            // Home Sections
            'flash_deals_title' => 'Flash Deals & Discounts',
            'flash_deals_sub' => 'Limited stock offers expiring soon',
            'categories_title' => 'Shop by Cyber Category',
            'categories_sub' => 'Handpicked premium hardware collections',
            'top_products_title' => 'Trending Cyber Battlestations',
            'top_products_sub' => 'Top selling gaming & productivity setups',
            'promo_banner_badge' => 'LIMITED TIME OFFER',
            'promo_banner_title' => 'Upgrade Your Cyber Battlestation with 20% Instant Discount',
            'promo_banner_sub' => 'Apply code CYBER20 during checkout. Valid for first 100 orders this week.',
            'promo_banner_btn' => 'Claim Discount ⚡',
            'trust_title' => 'Why Shoppers Trust NEXUS DOKAN',
            'trust_sub' => 'Standard warranty and express logistics across Bangladesh',
            'trust_1_title' => 'Fastest Home Delivery',
            'trust_1_sub' => '24h in Dhaka, 48h for other districts',
            'trust_2_title' => '100% Genuine Warranty',
            'trust_2_sub' => 'Official replacement guarantee',
            'trust_3_title' => 'Cash on Delivery',
            'trust_3_sub' => 'Inspect parcel before making payment',
            'trust_4_title' => '24/7 Dedicated Support',
            'trust_4_sub' => 'Live human chat & hotline assistance',
            'reviews_title' => 'Customer Reviews & Feedback',
            'reviews_sub' => 'Real experiences shared by verified tech enthusiasts',
            'add_to_cart' => 'Add to Cart',
            'buy_now' => 'Buy Now',
            'quick_view' => 'Quick View',
            'in_stock' => 'IN STOCK',
            'out_of_stock' => 'OUT OF STOCK',
            'discount' => 'OFF',
            'view_details' => 'View Details',

            // Cart & Drawer
            'cart_title' => 'Shopping Cart',
            'cart_empty' => 'Your cyber cart is currently empty.',
            'cart_subtotal' => 'Subtotal',
            'cart_checkout' => 'Proceed to Checkout',
            'cart_apply_coupon' => 'Apply Coupon',
            'coupon_code' => 'Coupon Code',
            'coupon_apply' => 'Apply',
            'coupon_discount' => 'Coupon Discount',
            'clear_cart' => 'Clear Cart',
            'continue_shopping' => 'Continue Shopping',

            // Checkout
            'checkout_title' => 'Express 1-Page Checkout',
            'shipping_details' => 'Delivery Information (Bangladesh)',
            'full_name' => 'Full Name',
            'phone_number' => 'Phone Number (11 Digits)',
            'email_address' => 'Email Address (Optional)',
            'district' => 'Select District / City',
            'delivery_address' => 'Full Street Address (House / Road / Area)',
            'delivery_notes' => 'Special Delivery Instructions (Optional)',
            'saved_address_btn' => 'Pick from Saved Addresses (1-Click)',
            'payment_method' => 'Payment Method',
            'cod_title' => 'Cash on Delivery (COD)',
            'cod_desc' => 'Pay cash when you receive the product at your door',
            'bkash_title' => 'bKash Direct / Merchant',
            'nagad_title' => 'Nagad Digital Payment',
            'place_order_btn' => 'Confirm Order Now 🛒',
            'order_summary' => 'Order Summary',
            'delivery_fee' => 'Delivery Charge',
            'total_amount' => 'Grand Total',

            // Product Details
            'reviews_rating' => 'Customer Reviews & Ratings',
            'verified_buyer' => 'Verified Buyer',
            'no_reviews_yet' => 'No reviews yet. Be the first to review this product!',
            'write_review' => 'Write a Customer Review',
            'your_name' => 'Your Name',
            'your_phone' => 'Phone Number (Optional)',
            'star_rating' => 'Star Rating',
            'your_comment' => 'Your Review / Feedback',
            'submit_review' => 'Submit Review',
            'similar_gear' => 'Similar Cyber Gear',
            'delivery_estimate' => 'Delivery Estimate & Charges',

            // Footer
            'about_store' => 'About Store',
            'about_store_text' => 'Next-generation eCommerce platform in Bangladesh providing authentic mechanical keyboards, ANC audio, holographic wearables and premium cyber lifestyle hardware with 24-48 hours home delivery across all 64 districts.',
            'quick_links' => 'Quick Links',
            'policy_legal' => 'Policies & Support',
            'all_rights_reserved' => 'All rights reserved.',

            // Admin Header & Controls
            'admin_brand_tagline' => 'COMMAND CENTER v2.6',
            'admin_command_center' => 'Command Center',
            'admin_super_admin' => 'Super Admin',
            'admin_live_store' => 'Live Storefront',
            'admin_live_active' => 'Live Store Active',
            'admin_logout' => 'Logout',
            'admin_dhaka_time' => 'Dhaka Time',

            // Admin Sidebar Folders & Menus
            'admin_dashboard' => 'Dashboard',
            'admin_sales_group' => 'Sales & Operations',
            'admin_orders' => 'Orders & Shipping',
            'admin_pnl' => 'Profit & Loss Audit',
            'admin_live_chat' => 'Live Support & AI Desk',
            'admin_live_chat_sub' => 'Realtime customer chat, agent desk & AI Auto-Pilot sales',
            'admin_ai_automation' => 'AI Automation & Voice Hub',
            'admin_ai_automation_sub' => 'Auto-SEO, WhatsApp Verification & AI Voice Calling Agent',
            'admin_inventory_group' => 'Products & Inventory',
            'admin_products' => 'All Products',
            'admin_categories' => 'Categories',
            'admin_suppliers' => 'Supplier Ledger',
            'admin_purchase_orders' => 'Purchase Orders & Stock',
            'admin_marketing_group' => 'Marketing & Funnels',
            'admin_landing_pages' => '1-Page Sales Funnels',
            'admin_cart_recovery' => 'Cart Recovery',
            'admin_sms_hub' => 'SMS Campaign Hub',
            'admin_reviews' => 'Customer Reviews',
            'admin_coupons' => 'Discount Coupons',
            'admin_vip_crm' => 'VIP Customers CRM',
            'admin_appearance_group' => 'Appearance & Pages',
            'admin_theme_studio' => 'Visual Theme Studio',
            'admin_policy_pages' => 'Policy & Legal Pages',
            'admin_settings_group' => 'Settings & Integrations',
            'admin_gateway_hub' => 'Gateway & API Hub',
            'admin_pixel_hub' => 'Pixel & GTM Tracking',
            'admin_staff' => 'Users & Staff Roles',
            'admin_blacklist' => 'Fraud Shield & Blacklist',
            'admin_store_settings' => 'General Store Settings',

            // Admin Dashboard Metrics
            'today_sales' => "Today's Sales",
            'today_sales_sub' => 'Live Settled Revenue',
            'today_orders' => "Today's New Orders",
            'today_orders_sub' => 'New Customer Orders',
            'pending_dispatch' => 'Pending Dispatch',
            'pending_dispatch_sub' => 'Awaiting Packing & Booking',
            'delivered_today' => 'Delivered Today',
            'delivered_today_sub' => 'Completed Handover',
            'in_transit' => 'Courier In-Transit',
            'in_transit_sub' => 'Steadfast & Pathao Hubs',
            'pending_cod' => 'Uncollected COD Receivable',
            'pending_cod_sub' => 'Courier Cash Settlement Due',
            'delivery_rate' => 'Delivery Success Rate',
            'delivery_rate_sub' => 'Low Return Ratio',
            'supplier_due' => 'Total Supplier Payable',
            'supplier_due_sub' => 'Accounts Payable',
            'sales_profit_chart' => '7-Day Revenue & Net Profit Trend',
            'chart_subtitle' => 'Daily Revenue vs Net Profit Margin',
            'revenue' => 'Gross Revenue',
            'net_profit' => 'Net Profit',
            'low_stock_warning' => 'Low Stock Urgent Alerts',
            'reorder_now' => '+ Reorder Stock',
            'recent_orders' => 'Recent Customer Orders',
            'best_sellers' => 'Top Selling Products',
            'view_all' => 'View All',
            'order_no' => 'Order #',
            'customer' => 'Customer',
            'amount' => 'Amount',
            'status' => 'Status',
            'courier' => 'Courier',
            'units_sold' => 'units sold',
            'only_left' => 'units remaining',
            'stock_sufficient' => 'All product inventory levels are healthy.',
            'no_pending_carts' => 'No pending abandoned carts right now.',
            'whatsapp_booster' => '1-Click WhatsApp Booster',
            'booked' => 'Booked',
            'send_courier' => 'Ship 🚀',
            'performance' => 'Performance',

            // Admin Marketing Pixels Page
            'pixel_hub_title' => 'Pixel, GTM & Marketing Tracking Hub',
            'pixel_hub_subtitle' => 'Configure, toggle on/off, and save tracking platforms independently as modular cards',
            'add_custom_pixel_btn' => '+ Add Custom Tracking Code 🎯',
            'meta_pixel_title' => 'Meta (Facebook) Pixel & CAPI',
            'meta_pixel_sub' => 'Facebook & Instagram Ads Conversion Tracking',
            'fb_pixel_id_label' => 'Facebook Pixel ID *',
            'fb_pixel_id_help' => 'Auto-tracks events: PageView, ViewContent, AddToCart, InitiateCheckout & Purchase (with value).',
            'fb_capi_token_label' => 'Conversion API (CAPI) Access Token (Optional)',
            'save_meta_pixel_btn' => 'Save Meta Pixel 💾',
            'test_btn' => 'Test 🎯',
            'live_active' => '● LIVE ACTIVE',
            'disabled' => '○ DISABLED',
            'gtm_title' => 'Google Tag Manager (GTM)',
            'gtm_sub' => 'Head & Body DataLayer Snippet Injection',
            'gtm_id_label' => 'GTM Container ID (e.g. GTM-554S4282) *',
            'gtm_id_help' => 'Automatically injects GTM head script and body noscript tags on every page.',
            'save_gtm_btn' => 'Save GTM 💾',
            'ga4_title' => 'Google Analytics 4 (GA4)',
            'ga4_sub' => 'Web Traffic & E-Commerce Event Analytics',
            'ga4_id_label' => 'GA4 Measurement ID (e.g. G-XXXXXXXXXX) *',
            'ga4_id_help' => 'Enter your Google Analytics 4 Property Measurement ID.',
            'save_ga4_btn' => 'Save GA4 💾',
            'tiktok_title' => 'TikTok Pixel',
            'tiktok_sub' => 'TikTok Ads Event & Conversion Tracking',
            'tiktok_id_label' => 'TikTok Pixel Code / ID *',
            'tiktok_id_help' => 'Enter your Pixel ID from TikTok Ads Manager.',
            'save_tiktok_btn' => 'Save TikTok Pixel 💾',
            'custom_scripts_title' => 'Custom Scripts & Webhook Injection',
            'custom_scripts_sub' => 'Domain Verification / Pinterest / Clarity / Hotjar',
            'header_scripts_label' => 'Custom <head> Scripts (Domain Verification & Tracking)',
            'footer_scripts_label' => 'Custom <body> Footer Scripts (Live Chat Widgets)',
            'save_custom_scripts_btn' => 'Save Custom Scripts 💾',
            'add_pixel_modal_title' => 'Add New Tracking Tag or Pixel 🎯',
            'tracker_name_label' => 'Tracker Name (e.g. Pinterest Pixel, Microsoft Clarity)',
            'script_code_label' => 'Script Code (Injected in <head> tag)',
            'save_and_activate_btn' => 'Save & Activate Tracking Tag 🚀',

            // Statuses
            'status_pending' => 'Pending',
            'status_processing' => 'Processing',
            'status_shipped' => 'Shipped',
            'status_delivered' => 'Delivered',
            'status_cancelled' => 'Cancelled',
            'status_paid' => 'Paid',
            'status_unpaid' => 'Unpaid',
        ],

        'bn' => [
            // Storefront Navbar & Global
            'nav_home' => 'হোম',
            'nav_shop' => 'সকল প্রোডাক্ট',
            'nav_categories' => 'ক্যাটাগরি',
            'nav_deals' => 'ফ্ল্যাশ ডিলস',
            'nav_track' => 'অর্ডার ট্র্যাকিং',
            'nav_spin' => 'লাকি হুইল',
            'nav_ai' => 'Aura AI বট',
            'nav_cart' => 'কার্ট',
            'nav_wishlist' => 'উইশলিস্ট',
            'nav_account' => 'আমার প্রোফাইল',
            'nav_login' => 'লগইন / রেজিস্টার',
            'nav_admin' => 'অ্যাডমিন কমান্ড সেন্টার',
            'search_placeholder' => 'সাইবার গ্যাজেট, মেকানিক্যাল কিবোর্ড, এয়ারবাডস খুঁজুন...',
            'free_shipping_notice' => 'সমগ্র বাংলাদেশে ৬৪ জেলায় দ্রুততম হোম ডেলিভারি সুবিধা',
            'currency_symbol' => '৳',
            'spin_win_btn' => 'স্পিন ও অফার',

            // Home & Hero Section
            'hero_badge' => '⚡ পরবর্তী প্রজন্মের গ্যাজেট ও লাইফস্টাইল • বাংলাদেশ',
            'hero_title_line_1' => 'আবিষ্কার করুন',
            'hero_title_gradient' => 'সাইবার প্রযুক্তি বিপ্লব',
            'hero_subtitle' => 'আপনার লাইফস্টাইল আপগ্রেড করুন প্রিমিয়াম মেকানিক্যাল সেটআপ, স্মার্ট ওয়্যারেবল ও গ্যাজেটের সাথে। সমগ্র বাংলাদেশে ২৪-৪৮ ঘণ্টার মধ্যে হোম ডেলিভারি।',
            'hero_btn_shop' => 'ক্যাটালগ দেখুন',
            'hero_btn_spin' => 'স্পিন করুন ও জিতুন ৳৫০০',
            'stat_customers_count' => '৫০ হাজার+',
            'stat_customers_label' => 'সন্তুষ্ট গ্রাহক',
            'stat_delivery_count' => '২৪ ঘণ্টা',
            'stat_delivery_label' => 'ঢাকা এক্সপ্রেস ডেলিভারি',
            'stat_genuine_count' => '১০০%',
            'stat_genuine_label' => 'খাঁটি ও অফিসিয়াল প্রডাক্ট',
            'featured_card_badge' => '🔥 শীর্ষ সাইবার গ্যাজেট',
            'featured_card_price' => '৳২,৯৫০',
            'featured_card_title' => 'AuraBlade ANC Pro এয়ারবাডস',
            'featured_card_sub' => '৪৫ মিলি-সেকেন্ড লো ল্যাটেন্সি • ৪৮ ডেসিবেল ANC',
            'featured_card_spec1' => 'v৫.৪ ডুয়েল স্ট্রিম',
            'featured_card_spec2' => '৪০ ঘণ্টা ব্যাটারি ব্যাকআপ',
            'featured_card_btn' => 'বিস্তারিত দেখুন ও কিনুন →',

            // Home Sections
            'flash_deals_title' => 'ধামাকা ফ্ল্যাশ সেল ও ডিসকাউন্ট',
            'flash_deals_sub' => 'সীমিত স্টক অফার — দ্রুত লুফে নিন',
            'categories_title' => 'ক্যাটাগরি অনুযায়ী কিনুন',
            'categories_sub' => 'আপনার পছন্দের গেমিং ও লাইফস্টাইল গ্যাজেট কালেকশন',
            'top_products_title' => 'জনপ্রিয় ট্রেন্ডিং গ্যাজেটসমূহ',
            'top_products_sub' => 'সেরা বিক্রিত গেমিং ও প্রডাক্টিভিটি সেটআপ',
            'promo_banner_badge' => 'সীমিত সময়ের বিশেষ অফার',
            'promo_banner_title' => 'আপনার সাইবার সেটআপ আপগ্রেড করুন ২০% ইনস্ট্যান্ট ছাড়ে',
            'promo_banner_sub' => 'চেকআউটের সময় CYBER20 কুপন কোড ব্যবহার করুন। এই সপ্তাহের প্রথম ১০০ জন অর্ডারের জন্য প্রযোজ্য।',
            'promo_banner_btn' => 'অফারটি লুফে নিন ⚡',
            'trust_title' => 'কেন সবাই NEXUS DOKAN-এ কেনাকাটা করেন?',
            'trust_sub' => 'নিশ্চিত অফিসিয়াল ওয়ারেন্টি ও দেশজুড়ে দ্রুততম ডেলিভারি ব্যবস্থা',
            'trust_1_title' => 'দ্রুততম হোম ডেলিভারি',
            'trust_1_sub' => 'ঢাকায় ২৪ ঘণ্টা ও অন্যান্য জেলায় ৪৮ ঘণ্টা',
            'trust_2_title' => '১০০% আসল পণ্যের গ্যারান্টি',
            'trust_2_sub' => 'অফিসিয়াল রিপ্লেসমেন্ট সুবিধা',
            'trust_3_title' => 'ক্যাশ অন ডেলিভারি সুবিধা',
            'trust_3_sub' => 'পণ্য হাতে পেয়ে মূল্য পরিশোধের সুবিধা',
            'trust_4_title' => '২৪/৭ ডেডিকেটেড সাপোর্ট',
            'trust_4_sub' => 'লাইভ চ্যাট ও হটলাইনে সরাসরি সহায়তা',
            'reviews_title' => 'ক্রেতাদের বাস্তব মতামত ও রিভিউ',
            'reviews_sub' => 'আমাদের যাচাইকৃত টেক প্রেমীদের সরাসরি অভিজ্ঞতা',
            'add_to_cart' => 'কার্টে যোগ করুন',
            'buy_now' => 'সরাসরি কিনুন',
            'quick_view' => 'এক নজরে দেখুন',
            'in_stock' => 'স্টকে আছে',
            'out_of_stock' => 'স্টক শেষ',
            'discount' => 'ছাড়',
            'view_details' => 'বিস্তারিত দেখুন',

            // Cart & Drawer
            'cart_title' => 'আপনার শপিং কার্ট',
            'cart_empty' => 'আপনার কার্টে বর্তমানে কোনো প্রোডাক্ট নেই।',
            'cart_subtotal' => 'মোট মূল্য',
            'cart_checkout' => 'অর্ডার কনফার্ম করুন',
            'cart_apply_coupon' => 'কুপন কোড দিন',
            'coupon_code' => 'ডিসকাউন্ট কুপন',
            'coupon_apply' => 'কুপন দিন',
            'coupon_discount' => 'কুপন ছাড়',
            'clear_cart' => 'কার্ট খালি করুন',
            'continue_shopping' => 'আরও কেনাকাটা করুন',

            // Checkout
            'checkout_title' => '১-পেজ সহজ চেকআউট',
            'shipping_details' => 'ডেলিভারি তথ্য (বাংলাদেশ)',
            'full_name' => 'আপনার পুরো নাম',
            'phone_number' => 'মোবাইল নম্বর (১১ ডিজিট)',
            'email_address' => 'ইমেইল অ্যাড্রেস (ঐচ্ছিক)',
            'district' => 'জেলা সিলেক্ট করুন',
            'delivery_address' => 'সম্পূর্ণ ঠিকানা (বাসা/রোড/এলাকা/থানা)',
            'delivery_notes' => 'বিশেষ কোনো ডেলিভারি নোট (ঐচ্ছিক)',
            'saved_address_btn' => 'সংরক্ষিত ঠিকানা থেকে সিলেক্ট করুন (১-ক্লিক)',
            'payment_method' => 'পেমেন্ট পদ্ধতি',
            'cod_title' => 'ক্যাশ অন ডেলিভারি (পণ্য পেয়ে মূল্য দিন)',
            'cod_desc' => 'ডেলিভারি ম্যানের কাছ থেকে পার্সেল বুঝে পেয়ে টাকা পরিশোধ করুন',
            'bkash_title' => 'বিকাশ সরাসরি পেমেন্ট',
            'nagad_title' => 'নগদ ডিজিটাল পেমেন্ট',
            'place_order_btn' => 'অর্ডার কনফার্ম করুন 🛒',
            'order_summary' => 'অর্ডারের বিবরণ',
            'delivery_fee' => 'ডেলিভারি চার্জ',
            'total_amount' => 'সর্বমোট প্রদেয় বিল',

            // Product Details
            'reviews_rating' => 'গ্রাহকদের রিভিউ ও রেটিং',
            'verified_buyer' => 'যাচাইকৃত ক্রেতা',
            'no_reviews_yet' => 'এই প্রোডাক্টে এখনো কোনো রিভিউ নেই। আপনিই প্রথম রিভিউ দিন!',
            'write_review' => 'আপনার রিভিউ লিখুন',
            'your_name' => 'আপনার নাম',
            'your_phone' => 'মোবাইল নম্বর (ঐচ্ছিক)',
            'star_rating' => 'স্টার রেটিং',
            'your_comment' => 'আপনার মতামত লিখুন',
            'submit_review' => 'রিভিউ সাবমিট করুন',
            'similar_gear' => 'সম্পর্কিত অন্যান্য প্রোডাক্ট',
            'delivery_estimate' => 'ডেলিভারি সময় ও চার্জের হিসাব',

            // Footer
            'about_store' => 'আমাদের সম্পর্কে',
            'about_store_text' => 'বাংলাদেশের প্রিমিয়াম সাইবার টেক ই-কমার্স প্ল্যাটফর্ম। মেকানিক্যাল কিবোর্ড, এএনসি অডিও ও স্মার্ট ওয়্যারেবল সমগ্র বাংলাদেশের ৬৪ জেলায় ২৪-৪৮ ঘণ্টার মধ্যে হোম ডেলিভারি দিয়ে থাকে।',
            'quick_links' => 'প্রয়োজনীয় লিংক',
            'policy_legal' => 'পলিসি ও সহায়তা',
            'all_rights_reserved' => 'সর্বস্বত্ব সংরক্ষিত।',

            // Admin Header & Controls
            'admin_brand_tagline' => 'কমান্ড সেন্টার সংস্করণ ২.৬',
            'admin_command_center' => 'কমান্ড সেন্টার',
            'admin_super_admin' => 'সুপার অ্যাডমিন',
            'admin_live_store' => 'লাইভ স্টোর দেখুন',
            'admin_live_active' => 'লাইভ স্টোর সচল',
            'admin_logout' => 'লগআউট',
            'admin_dhaka_time' => 'ঢাকা সময়',

            // Admin Sidebar Folders & Menus
            'admin_dashboard' => 'ড্যাশবোর্ড',
            'admin_sales_group' => 'অর্ডার ও সেলস',
            'admin_orders' => 'অর্ডার ও কুরিয়ার',
            'admin_pnl' => 'নিট প্রফিট অডিট',
            'admin_live_chat' => 'লাইভ সাপোর্ট ও এআই ডেস্ক',
            'admin_live_chat_sub' => 'রিয়েলটাইম কাস্টমার চ্যাট, এজেন্ট ডেস্ক ও এআই অটো-পাইলট',
            'admin_ai_automation' => 'এআই অটোমেশন ও ভয়েস হাব',
            'admin_ai_automation_sub' => 'অটো-এসইও, হোয়াটসঅ্যাপ ভেরিফিকেশন ও এআই ভয়েস কলিং',
            'admin_inventory_group' => 'প্রোডাক্ট ও গোডাউন',
            'admin_products' => 'সকল প্রোডাক্ট',
            'admin_categories' => 'ক্যাটাগরি',
            'admin_suppliers' => 'সাপ্লায়ার খতিয়ান',
            'admin_purchase_orders' => 'মাল ক্রয় ও স্টক',
            'admin_marketing_group' => 'মার্কেটিং ও ফানেল',
            'admin_landing_pages' => '১-পেজ ল্যান্ডিং ফানেল',
            'admin_cart_recovery' => 'কার্ট রিকভারি',
            'admin_sms_hub' => 'এসএমএস ক্যাম্পেইন হাব',
            'admin_reviews' => 'কাস্টমার রিভিউ',
            'admin_coupons' => 'ডিসকাউন্ট কুপন',
            'admin_vip_crm' => 'ভিআইপি গ্রাহক সিআরএম',
            'admin_appearance_group' => 'ডিজাইন ও পেজ',
            'admin_theme_studio' => 'ভিজ্যুয়াল থিম স্টুডিও',
            'admin_policy_pages' => 'পলিসি ও লিগ্যাল পেজ',
            'admin_settings_group' => 'সেটিংস ও এপিআই',
            'admin_gateway_hub' => 'গেটওয়ে ও এপিআই হাব',
            'admin_pixel_hub' => 'পিক্সেল ও ট্র্যাকিং',
            'admin_staff' => 'স্টাফ ও রোল',
            'admin_blacklist' => 'আইপি ও ফ্রড ব্লকলিস্ট',
            'admin_store_settings' => 'স্টোর সেটিংস',

            // Admin Dashboard Metrics
            'today_sales' => 'আজকের মোট সেলস',
            'today_sales_sub' => 'লাইভ নিশ্চিতকৃত রেভিনিউ',
            'today_orders' => 'আজকের নতুন অর্ডার',
            'today_orders_sub' => 'আজকের গ্রাহক অর্ডারসমূহ',
            'pending_dispatch' => 'প্যাকিং ও বুকিং পেন্ডিং',
            'pending_dispatch_sub' => 'কুরিয়ারে বুকিংয়ের অপেক্ষায়',
            'delivered_today' => 'আজকে ডেলিভারি সম্পন্ন',
            'delivered_today_sub' => 'কাস্টমার রিসিভ করেছে',
            'in_transit' => 'কুরিয়ারে ট্রানজিটে আছে',
            'in_transit_sub' => 'Steadfast ও Pathao কুরিয়ারে',
            'pending_cod' => 'কুরিয়ার থেকে ক্যাশ কালেকশন বাকি',
            'pending_cod_sub' => 'কুরিয়ার পেমেন্ট সেটেলমেন্ট বাকি',
            'delivery_rate' => 'সফল ডেলিভারি রেশিও',
            'delivery_rate_sub' => 'লো রিটার্ন ও হাই সাকসেস',
            'supplier_due' => 'সাপ্লায়ার মোট বকেয়া',
            'supplier_due_sub' => 'সাপ্লায়ারদের দেনা পাওনা',
            'sales_profit_chart' => '৭ দিনের সেলস ও নিট প্রফিট অ্যানালিটিক্স',
            'chart_subtitle' => 'দৈনিক বিক্রি ও প্রকৃত লাভের হিসাব',
            'revenue' => 'মোট বিক্রি',
            'net_profit' => 'প্রকৃত লাভ',
            'low_stock_warning' => 'জরুরি লো-স্টক সতর্কবার্তা',
            'reorder_now' => '+ রিস্টক করুন',
            'recent_orders' => 'সাম্প্রতিক কাস্টমার অর্ডারসমূহ',
            'best_sellers' => 'শীর্ষ বিক্রিত প্রোডাক্ট',
            'view_all' => 'সকল দেখুন',
            'order_no' => 'অর্ডার #',
            'customer' => 'গ্রাহক',
            'amount' => 'টাকার পরিমাণ',
            'status' => 'স্ট্যাটাস',
            'courier' => 'কুরিয়ার',
            'units_sold' => 'টি বিক্রি হয়েছে',
            'only_left' => 'টি অবশিষ্ট আছে',
            'stock_sufficient' => 'সব প্রোডাক্টের স্টক পর্যাপ্ত আছে।',
            'no_pending_carts' => 'কোনো পেন্ডিং কার্ট নেই।',
            'whatsapp_booster' => '১-ক্লিক হোয়াটসঅ্যাপ রিকভারি',
            'booked' => 'বুকিং সম্পন্ন',
            'send_courier' => 'পাঠান 🚀',
            'performance' => 'পারফর্মেন্স',

            // Admin Marketing Pixels Page
            'pixel_hub_title' => 'পিক্সেল, জিটিএম ও মার্কেটিং ট্র্যাকিং হাব',
            'pixel_hub_subtitle' => 'প্রতিটি ট্র্যাকিং প্ল্যাটফর্ম আলাদা কার্ড হিসেবে কনফিগার, অন/অফ এবং সিঙ্গেল সেভ করুন',
            'add_custom_pixel_btn' => '+ নতুন ট্র্যাকিং কোড যোগ করুন 🎯',
            'meta_pixel_title' => 'মেটা (ফেসবুক) পিক্সেল ও কনভার্সন এপিআই',
            'meta_pixel_sub' => 'ফেসবুক ও ইনস্টাগ্রাম অ্যাডস ইভেন্ট ট্র্যাকিং',
            'fb_pixel_id_label' => 'ফেসবুক পিক্সেল আইডি *',
            'fb_pixel_id_help' => 'স্বয়ংক্রিয় ইভেন্ট ট্র্যাকিং: PageView, ViewContent, AddToCart, InitiateCheckout ও Purchase (টাকার পরিমাণ সহ)।',
            'fb_capi_token_label' => 'কনভার্সন এপিআই (CAPI) অ্যাক্সেস টোকেন (ঐচ্ছিক)',
            'save_meta_pixel_btn' => 'মেটা পিক্সেল সেভ করুন 💾',
            'test_btn' => 'টেস্ট করুন 🎯',
            'live_active' => '● সক্রিয় লাইভ',
            'disabled' => '○ বন্ধ আছে',
            'gtm_title' => 'গুগল ট্যাগ ম্যানেজার (GTM)',
            'gtm_sub' => 'হেড ও বডি ডাটালেয়ার কোড ইনজেকশন',
            'gtm_id_label' => 'জিটিএম কন্টেইনার আইডি (e.g. GTM-554S4282) *',
            'gtm_id_help' => 'GTM হেড স্ক্রিপ্ট ও বডি নোস্ক্রিপ্ট স্বয়ংক্রিয়ভাবে পুরো ওয়েবসাইটে ইনজেক্ট হবে।',
            'save_gtm_btn' => 'জিটিএম সেভ করুন 💾',
            'ga4_title' => 'গুগল অ্যানালিটিক্স ৪ (GA4)',
            'ga4_sub' => 'ওয়েব ট্রাফিক ও ই-কমার্স অ্যানালিটিক্স',
            'ga4_id_label' => 'জিএ৪ মেজারমেন্ট আইডি (e.g. G-XXXXXXXXXX) *',
            'ga4_id_help' => 'গুগল অ্যানালিটিক্স প্রপার্টির Measurement ID বসান।',
            'save_ga4_btn' => 'জিএ৪ সেভ করুন 💾',
            'tiktok_title' => 'টিকটক পিক্সেল',
            'tiktok_sub' => 'টিকটক অ্যাডস ইভেন্ট ও কনভার্সন ট্র্যাকিং',
            'tiktok_id_label' => 'টিকটক পিক্সেল কোড / আইডি *',
            'tiktok_id_help' => 'TikTok Ads Manager থেকে প্রাপ্ত Pixel ID বসান।',
            'save_tiktok_btn' => 'টিকটক পিক্সেল সেভ করুন 💾',
            'custom_scripts_title' => 'কাস্টম স্ক্রিপ্ট ও ট্র্যাকিং ইনজেকশন',
            'custom_scripts_sub' => 'ডোমেন ভেরিফিকেশন / পিন্টারেস্ট / ক্ল্যারিটি / হটজার',
            'header_scripts_label' => 'কাস্টম <head> স্ক্রিপ্ট (ডোমেন ভেরিফিকেশন ও ট্র্যাকিং)',
            'footer_scripts_label' => 'কাস্টম <body> ফুটার স্ক্রিপ্ট (লাইভ চ্যাট উইজেট)',
            'save_custom_scripts_btn' => 'কাস্টম স্ক্রিপ্ট সংরক্ষণ করুন 💾',
            'add_pixel_modal_title' => 'নতুন ট্র্যাকিং ট্যাগ বা পিক্সেল যোগ করুন 🎯',
            'tracker_name_label' => 'ট্র্যাকারের নাম (e.g. Pinterest Pixel, Microsoft Clarity)',
            'script_code_label' => 'স্ক্রিপ্ট কোড (<head> ট্যাগে যুক্ত হবে)',
            'save_and_activate_btn' => 'ট্র্যাকিং কোড সেভ ও সক্রিয় করুন 🚀',

            // Statuses
            'status_pending' => 'পেন্ডিং',
            'status_processing' => 'প্রসেসিং',
            'status_shipped' => 'শিপড',
            'status_delivered' => 'ডেলিভার্ড',
            'status_cancelled' => 'বাতিল',
            'status_paid' => 'পরিশোধিত',
            'status_unpaid' => 'অপরিশোধিত',
        ],
    ];

    public static function get(string $key, ?string $default = null): string
    {
        $locale = session('app_locale', 'bn');
        return self::$dictionary[$locale][$key] ?? self::$dictionary['en'][$key] ?? ($default ?? $key);
    }

    public static function getLocale(): string
    {
        return session('app_locale', 'bn');
    }

    public static function setLocale(string $locale): void
    {
        if (in_array($locale, ['bn', 'en'])) {
            session(['app_locale' => $locale]);
        }
    }

    public static function toggle(): string
    {
        $current = self::getLocale();
        $next = ($current === 'bn') ? 'en' : 'bn';
        self::setLocale($next);
        return $next;
    }
}
